/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var d=Object.defineProperty;var f=Object.getOwnPropertyDescriptor;var a=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var h=(e,r)=>{for(var o in r)d(e,o,{get:r[o],enumerable:!0})},p=(e,r,o,t)=>{if(r&&typeof r=="object"||typeof r=="function")for(let n of a(r))!g.call(e,n)&&n!==o&&d(e,n,{get:()=>r[n],enumerable:!(t=f(r,n))||t.enumerable});return e};var y=e=>p(d({},"__esModule",{value:!0}),e);var l={};h(l,{default:()=>i});module.exports=y(l);var u=require("@codemirror/language"),c=require("@codemirror/state"),m=require("obsidian"),i=class extends m.Plugin{async onload(){this.registerEditorExtension(c.Prec.high(_()))}onunload(){}};function _(){let e=CodeMirror.getMode({},{name:"hypermd"});return u.StreamLanguage.define({...e,token(r,o){return o.quote&&r.match(/^```/)?(o.__iscode=!o.__iscode,null):o.quote&&o.__iscode&&r.match(/^</)?"bad-<":e.token(r,o)}})}
